version: 0.1
environment_variables:
    plaintext:
        S3_BUCKET: "ct-frontend.lfsa.com"
        BUILD_ENV: "prod"
phases:
    install:
        commands:
            - echo Installing source NPM dependencies...
            - npm install
            - npm install -g @angular/cli
    build:
        commands:
            - echo Build started on `date`
            - ng build -e=prod --prod --no-sourcemap --aot=false
    post_build:
         commands:
            - aws s3 cp dist s3://ct-frontend.lfsa.com --recursive
            - echo Build completed on `date`
artifacts:
    files:
        - '**/*'
    base-directory: 'dist*'
    discard-paths: yes
