export const HEADER_EVENTS = {
    RFC: 'HEADER_RFC.CHANGED',
    FILTERS: 'HEADER_FILTERS.CHANGED'
}

export const RECIEVED_EVENTS = {
    RELOAD: 'RECIEVED_EVENTS.RELOAD'
}

export const MANAGE_RFC_EVENTS = {
    RELOAD: 'MANAGE_RFC_EVENTS.RELOAD'
}

export const BANK_ACCOUNTS_EVENTS = {
    RELOAD: 'MANAGE_RFC_EVENTS.RELOAD'
}

export const SEARCH = {
    REFRESH: 'SEARCH_FILTER'
}